# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager


PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
DRIVER_BIN = os.path.join(PROJECT_ROOT, "chromedriver")


class TestTest1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test1(self):
        self.driver.get("https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login")
        self.driver.set_window_size(1378, 875)
        time.sleep(1)
        self.driver.find_element(By.XPATH, "/html/body/div/div/div[2]/div/div[1]/div[2]/button").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//div[2]/div/div/button").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//input[@type=\'text\']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//input[@type=\'text\']").send_keys("Charles")
        time.sleep(1)
        self.driver.find_element(By.XPATH, "(//input[@type=\'text\'])[2]").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "(//input[@type=\'text\'])[2]").send_keys("Raj")
        time.sleep(1)
        self.driver.find_element(By.XPATH, "(//input[@type=\'text\'])[3]").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "(//input[@type=\'text\'])[3]").send_keys("123456")
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//button[@value=\'\']").click()
        time.sleep(1)
        # self.send_keys(Keys.RETURN)
        self.driver.switch_to.alert.accept()

        self.driver.find_element(By.XPATH, "//button[contains(.,\'Open Account\')]").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "userSelect").click()
        time.sleep(1)
        dropdown = self.driver.find_element(By.ID, "userSelect")
        time.sleep(1)
        dropdown.find_element(By.XPATH, "//option[. = 'Charles Raj']").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "currency").click()
        time.sleep(1)
        dropdown = self.driver.find_element(By.ID, "currency")
        time.sleep(1)
        dropdown.find_element(By.XPATH, "//option[. = 'Dollar']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//button[@value=\'\']").click()
        time.sleep(1)
        self.driver.switch_to.alert.accept()
        self.driver.find_element(By.XPATH, "//button[3]").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//td[5]/button").click()
        time.sleep(1)

